// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtFlVqu2oYfrJh0AMNiMqjQ0SVbHCx0PE',
    appId: '1:432749745245:web:496a599b6af1ea8f0129b4',
    messagingSenderId: '432749745245',
    projectId: 'sustainabilitytoronto',
    authDomain: 'sustainabilitytoronto.firebaseapp.com',
    storageBucket: 'sustainabilitytoronto.appspot.com',
    measurementId: 'G-WK0S3CRNNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiRcIr7R5yHOu17dtqmnZ_2KqLz2PUhiU',
    appId: '1:432749745245:android:349dbece1bf3d7e40129b4',
    messagingSenderId: '432749745245',
    projectId: 'sustainabilitytoronto',
    storageBucket: 'sustainabilitytoronto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDunejTaTjgt2MLcv_4JFqsOmG7oHSS_gA',
    appId: '1:432749745245:ios:7acc37bc773331fc0129b4',
    messagingSenderId: '432749745245',
    projectId: 'sustainabilitytoronto',
    storageBucket: 'sustainabilitytoronto.appspot.com',
    iosBundleId: 'com.bpd.sustainablefootprint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDunejTaTjgt2MLcv_4JFqsOmG7oHSS_gA',
    appId: '1:432749745245:ios:23841fe4e221b8660129b4',
    messagingSenderId: '432749745245',
    projectId: 'sustainabilitytoronto',
    storageBucket: 'sustainabilitytoronto.appspot.com',
    iosBundleId: 'com.example.sustainableFootprint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtFlVqu2oYfrJh0AMNiMqjQ0SVbHCx0PE',
    appId: '1:432749745245:web:317098dc8b6ccbf20129b4',
    messagingSenderId: '432749745245',
    projectId: 'sustainabilitytoronto',
    authDomain: 'sustainabilitytoronto.firebaseapp.com',
    storageBucket: 'sustainabilitytoronto.appspot.com',
    measurementId: 'G-CH08EYF3WQ',
  );

}